package pt.ipvc.vending.domain.enums;

public enum AuditAction {
    CREATE,
    UPDATE,
    DELETE,
    STATUS_CHANGE,
    LOGIN,
    LOGIN_FAILED,
    LOGOUT,
    ACCEPT,
    REJECT,
    COUNTER_PROPOSAL,
    TERMINATION_REQUEST,
    INSTALLATION_COMPLETED,
    INSTALLATION_DELAYED,
    ACCOUNT_REQUEST_SUBMITTED,
    ACCOUNT_REQUEST_APPROVED,
    ACCOUNT_REQUEST_REJECTED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    PASSWORD_RESET_FAILED
}
